import { Property, Conversation } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Villa Blanche de Sidi Bou Said',
    type: 'Villa',
    location: 'Sidi Bou Said',
    wilaya: 'Ben Arous',
    description:
      'Nichée au cœur du pittoresque village de Sidi Bou Said, cette villa exceptionnelle offre une vue imprenable sur la Méditerranée. Avec ses murs blancs immaculés et ses portes bleues caractéristiques, elle incarne l\'essence de l\'architecture tunisienne traditionnelle. La piscine à débordement donne l\'impression de se fondre dans la mer. Profitez de matinées ensoleillées sur la grande terrasse, sirotez un thé à la menthe en admirant le coucher de soleil sur la baie de Tunis.',
    shortDescription: 'Villa avec vue mer, architecture traditionnelle bleue et blanche',
    images: [
      'https://picsum.photos/seed/sidi1/800/600',
      'https://picsum.photos/seed/sidi2/800/600',
      'https://picsum.photos/seed/sidi3/800/600',
      'https://picsum.photos/seed/sidi4/800/600',
      'https://picsum.photos/seed/sidi5/800/600',
    ],
    price: 450,
    cleaningFee: 80,
    guests: 8,
    bedrooms: 4,
    bathrooms: 3,
    beds: 5,
    rating: 4.95,
    reviewCount: 47,
    amenities: ['WiFi', 'Piscine', 'Climatisation', 'Cuisine équipée', 'Parking', 'Terrasse', 'Vue mer', 'Barbecue', 'Lave-linge'],
    houseRules: [
      { title: 'Arrivée', description: 'Après 15h00' },
      { title: 'Départ', description: 'Avant 11h00' },
      { title: 'Pas de cigarette', description: 'Interdit de fumer dans tout le logement' },
      { title: 'Pas de fêtes', description: 'Pas de fêtes ni d\'événements non autorisés' },
      { title: 'Animaux non admis', description: 'Les animaux de compagnie ne sont pas autorisés' },
      { title: 'Calme nocturne', description: 'Pas de nuisances sonores après 22h00' },
      { title: 'Maximum 8 voyageurs', description: 'Le nombre maximum de voyageurs ne doit pas être dépassé' },
    ],
    host: {
      id: 'h1',
      name: 'Yasmine Ben Ali',
      avatar: 'https://i.pravatar.cc/150?img=47',
      joinDate: 'Janvier 2019',
      responseRate: 98,
      responseTime: 'Dans l\'heure',
      isSuperhost: true,
      bio: 'Passionnée de culture tunisienne, j\'adore partager la beauté de notre pays avec les voyageurs du monde entier. Sidi Bou Said est ma ville natale et je suis fière de vous y accueillir.',
    },
    reviews: [
      { id: 'r1', author: 'Marie L.', avatar: 'https://i.pravatar.cc/150?img=1', date: 'Avril 2024', rating: 5, comment: 'Endroit magnifique, vue époustouflante sur la mer. Yasmine est une hôte formidable, très attentionnée !' },
      { id: 'r2', author: 'Ahmed K.', avatar: 'https://i.pravatar.cc/150?img=11', date: 'Mars 2024', rating: 5, comment: 'Villa parfaite, propre et bien équipée. Le village de Sidi Bou Said est à couper le souffle. On reviendra !' },
      { id: 'r3', author: 'Sophie M.', avatar: 'https://i.pravatar.cc/150?img=5', date: 'Février 2024', rating: 5, comment: 'Séjour inoubliable dans ce havre de paix. La piscine est superbe et la vue mer est exceptionnelle.' },
    ],
    minNights: 2,
    available: true,
    lat: 36.869,
    lng: 10.342,
  },
  {
    id: '2',
    title: 'Riad Djerba Al Amal',
    type: 'Riad',
    location: 'Houmt Souk, Djerba',
    wilaya: 'Médenine',
    description:
      'Ce riad authentique au cœur de la médina de Djerba est un véritable joyau architectural. Construit selon les traditions berbères et arabes, il offre un espace de vie unique avec son patio central orné d\'une fontaine en zellige. Les 3 chambres sont décorées avec des textiles locaux et des meubles en bois sculpté. Le toit-terrasse offre une vue panoramique sur les toits blancs de Houmt Souk et la mer au loin.',
    shortDescription: 'Riad authentique avec patio, fontaine et terrasse panoramique',
    images: [
      'https://picsum.photos/seed/djerba1/800/600',
      'https://picsum.photos/seed/djerba2/800/600',
      'https://picsum.photos/seed/djerba3/800/600',
      'https://picsum.photos/seed/djerba4/800/600',
      'https://picsum.photos/seed/djerba5/800/600',
    ],
    price: 280,
    cleaningFee: 60,
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    beds: 4,
    rating: 4.88,
    reviewCount: 32,
    amenities: ['WiFi', 'Climatisation', 'Cuisine équipée', 'Terrasse', 'Patio', 'Parking proche'],
    houseRules: [
      { title: 'Arrivée', description: 'Après 15h00' },
      { title: 'Départ', description: 'Avant 11h00' },
      { title: 'Pas de cigarette', description: 'Interdit de fumer à l\'intérieur' },
      { title: 'Pas de fêtes', description: 'Lieu calme, pas de fêtes' },
      { title: 'Animaux non admis', description: 'Les animaux ne sont pas acceptés' },
      { title: 'Calme nocturne', description: 'Respect du calme après 22h00' },
    ],
    host: {
      id: 'h2',
      name: 'Karim Mzoughi',
      avatar: 'https://i.pravatar.cc/150?img=12',
      joinDate: 'Mars 2020',
      responseRate: 95,
      responseTime: 'Dans les 2 heures',
      isSuperhost: false,
      bio: 'Natif de Djerba, j\'ai rénové ce riad familial pour partager la richesse culturelle de l\'île avec les visiteurs.',
    },
    reviews: [
      { id: 'r4', author: 'Jean-Pierre D.', avatar: 'https://i.pravatar.cc/150?img=3', date: 'Mai 2024', rating: 5, comment: 'Riad magnifique, dépaysement total ! Le patio est un vrai havre de paix.' },
      { id: 'r5', author: 'Leila B.', avatar: 'https://i.pravatar.cc/150?img=20', date: 'Avril 2024', rating: 4, comment: 'Très beau logement, décoration soignée. Karim est un hôte accueillant.' },
    ],
    minNights: 2,
    available: true,
    lat: 33.876,
    lng: 10.857,
  },
  {
    id: '3',
    title: 'Villa Jasmin Hammamet',
    type: 'Villa',
    location: 'Hammamet Nord',
    wilaya: 'Nabeul',
    description:
      'Grande villa de luxe à deux pas de la plage de Hammamet. Avec sa piscine privée entourée de jasmin et d\'orangers, c\'est le cadre idéal pour un séjour en famille ou entre amis. La villa dispose de 5 chambres climatisées, d\'une grande cuisine équipée, d\'un salon spacieux et d\'une terrasse donnant sur le jardin. À 300 mètres de la mer et à 10 minutes à pied du centre animé de Hammamet.',
    shortDescription: 'Villa de luxe avec piscine privée, jardin fleuri, proche plage',
    images: [
      'https://picsum.photos/seed/hamm1/800/600',
      'https://picsum.photos/seed/hamm2/800/600',
      'https://picsum.photos/seed/hamm3/800/600',
      'https://picsum.photos/seed/hamm4/800/600',
      'https://picsum.photos/seed/hamm5/800/600',
    ],
    price: 580,
    cleaningFee: 100,
    guests: 10,
    bedrooms: 5,
    bathrooms: 4,
    beds: 7,
    rating: 4.92,
    reviewCount: 63,
    amenities: ['WiFi', 'Piscine', 'Climatisation', 'Cuisine équipée', 'Parking', 'Terrasse', 'Jardin', 'Barbecue', 'Lave-linge', 'Télévision'],
    houseRules: [
      { title: 'Arrivée', description: 'Après 15h00' },
      { title: 'Départ', description: 'Avant 11h00' },
      { title: 'Pas de cigarette', description: 'Fumeurs uniquement en extérieur' },
      { title: 'Fêtes autorisées avec accord', description: 'Événements possible avec accord préalable de l\'hôte' },
      { title: 'Animaux avec accord', description: 'Animaux acceptés sous conditions' },
      { title: 'Calme nocturne', description: 'Musique à volume raisonnable après 23h' },
    ],
    host: {
      id: 'h3',
      name: 'Nadia Sellami',
      avatar: 'https://i.pravatar.cc/150?img=45',
      joinDate: 'Juin 2018',
      responseRate: 99,
      responseTime: 'Dans l\'heure',
      isSuperhost: true,
      bio: 'Gestionnaire de propriétés depuis 6 ans, je mets tout en œuvre pour que votre séjour soit parfait. La villa est entretenue avec soin.',
    },
    reviews: [
      { id: 'r6', author: 'François T.', avatar: 'https://i.pravatar.cc/150?img=7', date: 'Juin 2024', rating: 5, comment: 'Villa superbe, piscine parfaite, Nadia est très réactive. Séjour 10/10 !' },
      { id: 'r7', author: 'Amira N.', avatar: 'https://i.pravatar.cc/150?img=22', date: 'Mai 2024', rating: 5, comment: 'Magnifique villa, très propre et bien équipée. La piscine et le jardin sont un bonheur.' },
      { id: 'r8', author: 'Thomas B.', avatar: 'https://i.pravatar.cc/150?img=9', date: 'Avril 2024', rating: 4, comment: 'Super séjour en famille. Villa spacieuse et bien placée. On recommande !' },
    ],
    minNights: 3,
    available: true,
    lat: 36.398,
    lng: 10.617,
  },
  {
    id: '4',
    title: 'Appartement Médina de Tunis',
    type: 'Appartement',
    location: 'Médina, Tunis',
    wilaya: 'Tunis',
    description:
      'Appartement rénové au cœur de la Médina de Tunis, classée au patrimoine mondial de l\'UNESCO. Situé dans une ancienne maison traditionnelle (dar), cet appartement de charme allie authenticité et confort moderne. À deux pas des souks, de la Grande Mosquée Zitouna et du musée du Bardo. Idéal pour découvrir la vie locale et l\'artisanat tunisien.',
    shortDescription: 'Appartement authentique dans la Médina classée UNESCO',
    images: [
      'https://picsum.photos/seed/tunis1/800/600',
      'https://picsum.photos/seed/tunis2/800/600',
      'https://picsum.photos/seed/tunis3/800/600',
      'https://picsum.photos/seed/tunis4/800/600',
      'https://picsum.photos/seed/tunis5/800/600',
    ],
    price: 180,
    cleaningFee: 40,
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    beds: 3,
    rating: 4.75,
    reviewCount: 28,
    amenities: ['WiFi', 'Climatisation', 'Cuisine équipée', 'Vue médina'],
    houseRules: [
      { title: 'Arrivée', description: 'Après 14h00' },
      { title: 'Départ', description: 'Avant 11h00' },
      { title: 'Pas de cigarette', description: 'Interdit de fumer' },
      { title: 'Pas de fêtes', description: 'Appartement en copropriété, respect des voisins' },
      { title: 'Animaux non admis', description: 'Pas d\'animaux' },
      { title: 'Calme nocturne', description: 'Silence après 22h (règlement de copropriété)' },
    ],
    host: {
      id: 'h4',
      name: 'Omar Gharbi',
      avatar: 'https://i.pravatar.cc/150?img=15',
      joinDate: 'Septembre 2021',
      responseRate: 90,
      responseTime: 'Dans les 3 heures',
      isSuperhost: false,
      bio: 'Architecte et amoureux du patrimoine, j\'ai restauré cet appartement en respectant l\'âme de la médina.',
    },
    reviews: [
      { id: 'r9', author: 'Claire P.', avatar: 'https://i.pravatar.cc/150?img=6', date: 'Mars 2024', rating: 5, comment: 'Lieu magique au cœur de la médina ! Omar est très attentionné et connaît parfaitement le quartier.' },
      { id: 'r10', author: 'Rami A.', avatar: 'https://i.pravatar.cc/150?img=18', date: 'Janvier 2024', rating: 4, comment: 'Appartement charmant, bien situé. Quelques bruits de la médina la nuit mais c\'est le charme du lieu.' },
    ],
    minNights: 1,
    available: true,
    lat: 36.798,
    lng: 10.171,
  },
  {
    id: '5',
    title: 'Dar Sousse Bord de Mer',
    type: 'Maison',
    location: 'Sousse Nord',
    wilaya: 'Sousse',
    description:
      'Maison de vacances directement sur la plage à Sousse, la "Perle du Sahel". Réveillez-vous au son des vagues et profitez d\'un accès direct à la mer depuis votre terrasse. La maison dispose de 3 chambres confortables, d\'un salon avec vue mer et d\'une terrasse équipée pour les repas en plein air. Proche du port de Sousse et des restaurants de fruits de mer.',
    shortDescription: 'Maison bord de mer avec accès direct à la plage',
    images: [
      'https://picsum.photos/seed/sousse1/800/600',
      'https://picsum.photos/seed/sousse2/800/600',
      'https://picsum.photos/seed/sousse3/800/600',
      'https://picsum.photos/seed/sousse4/800/600',
      'https://picsum.photos/seed/sousse5/800/600',
    ],
    price: 320,
    cleaningFee: 65,
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    beds: 4,
    rating: 4.85,
    reviewCount: 41,
    amenities: ['WiFi', 'Climatisation', 'Cuisine équipée', 'Parking', 'Terrasse', 'Vue mer', 'Accès plage', 'Barbecue'],
    houseRules: [
      { title: 'Arrivée', description: 'Après 15h00' },
      { title: 'Départ', description: 'Avant 10h00' },
      { title: 'Pas de cigarette', description: 'Fumeurs en terrasse uniquement' },
      { title: 'Pas de fêtes', description: 'Pas d\'événements' },
      { title: 'Animaux non admis', description: 'Pas d\'animaux de compagnie' },
      { title: 'Calme nocturne', description: 'Calme après 22h' },
    ],
    host: {
      id: 'h5',
      name: 'Fatima Khaldi',
      avatar: 'https://i.pravatar.cc/150?img=48',
      joinDate: 'Avril 2020',
      responseRate: 96,
      responseTime: 'Dans les 2 heures',
      isSuperhost: false,
      bio: 'Je loue cette maison familiale depuis 4 ans. Mon but : vous offrir le confort d\'un vrai chez-vous face à la mer.',
    },
    reviews: [
      { id: 'r11', author: 'Nicolas F.', avatar: 'https://i.pravatar.cc/150?img=8', date: 'Juillet 2024', rating: 5, comment: 'Vue mer incroyable, accès direct à la plage. La maison est parfaitement équipée.' },
      { id: 'r12', author: 'Sarra M.', avatar: 'https://i.pravatar.cc/150?img=25', date: 'Juin 2024', rating: 5, comment: 'Magnifique séjour ! La maison est propre, bien située, et Fatima est très sympa.' },
    ],
    minNights: 2,
    available: true,
    lat: 35.825,
    lng: 10.638,
  },
  {
    id: '6',
    title: 'Chalet Tabarka Forêt de Pins',
    type: 'Maison',
    location: 'Tabarka',
    wilaya: 'Jendouba',
    description:
      'Chalet en bois niché dans la forêt de pins de Tabarka, à quelques minutes des plus belles plages de la côte nord. Profitez d\'un air pur et d\'une nature exceptionnelle. Le chalet dispose d\'une cheminée pour les soirées fraîches, d\'une terrasse en bois avec vue sur les pins et d\'un équipement complet pour un séjour en toute autonomie. Idéal pour les amateurs de randonnée, plongée et plage.',
    shortDescription: 'Chalet bois en forêt de pins, proche plage et nature sauvage',
    images: [
      'https://picsum.photos/seed/tabarka1/800/600',
      'https://picsum.photos/seed/tabarka2/800/600',
      'https://picsum.photos/seed/tabarka3/800/600',
      'https://picsum.photos/seed/tabarka4/800/600',
      'https://picsum.photos/seed/tabarka5/800/600',
    ],
    price: 220,
    cleaningFee: 50,
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    beds: 3,
    rating: 4.90,
    reviewCount: 19,
    amenities: ['WiFi', 'Cheminée', 'Cuisine équipée', 'Terrasse', 'Parking', 'Randonnée'],
    houseRules: [
      { title: 'Arrivée', description: 'Après 15h00' },
      { title: 'Départ', description: 'Avant 11h00' },
      { title: 'Pas de cigarette à l\'intérieur', description: 'Fumer uniquement en extérieur loin de la forêt' },
      { title: 'Pas de feux en extérieur', description: 'Risque incendie : barbecue uniquement dans l\'espace dédié' },
      { title: 'Respect de la nature', description: 'Ne pas laisser de déchets dans la forêt' },
      { title: 'Calme nocturne', description: 'Silence complet après 22h' },
    ],
    host: {
      id: 'h6',
      name: 'Amine Belhadj',
      avatar: 'https://i.pravatar.cc/150?img=14',
      joinDate: 'Novembre 2021',
      responseRate: 94,
      responseTime: 'Dans les 4 heures',
      isSuperhost: false,
      bio: 'Guide de randonnée et amoureux de la nature, je propose ce chalet pour ceux qui veulent se ressourcer dans la forêt de Tabarka.',
    },
    reviews: [
      { id: 'r13', author: 'Isabelle R.', avatar: 'https://i.pravatar.cc/150?img=4', date: 'Août 2024', rating: 5, comment: 'Chalet très chaleureux, cadre magnifique. Amine a été d\'une grande aide pour les randonnées.' },
      { id: 'r14', author: 'Youssef H.', avatar: 'https://i.pravatar.cc/150?img=16', date: 'Juillet 2024', rating: 5, comment: 'Parfait pour se déconnecter ! La forêt est apaisante et les plages de Tabarka sont superbes.' },
    ],
    minNights: 2,
    available: true,
    lat: 36.958,
    lng: 8.756,
  },
  {
    id: '7',
    title: 'Maison Tozeur Oasis',
    type: 'Maison',
    location: 'Tozeur',
    wilaya: 'Tozeur',
    description:
      'Maison traditionnelle en brique de pisé au cœur de la palmeraie de Tozeur, porte du Sahara. Cette demeure authentique, construite selon l\'architecture locale en briques en relief, offre une expérience unique aux portes du désert. Dormez sous les étoiles sur la terrasse, explorez les dunes à chameau et visitez les chotts salés. La maison est entourée d\'un jardin tropical avec palmiers dattiers et citronniers.',
    shortDescription: 'Maison traditionnelle pisé dans la palmeraie, porte du Sahara',
    images: [
      'https://picsum.photos/seed/tozeur1/800/600',
      'https://picsum.photos/seed/tozeur2/800/600',
      'https://picsum.photos/seed/tozeur3/800/600',
      'https://picsum.photos/seed/tozeur4/800/600',
      'https://picsum.photos/seed/tozeur5/800/600',
    ],
    price: 250,
    cleaningFee: 55,
    guests: 5,
    bedrooms: 2,
    bathrooms: 1,
    beds: 3,
    rating: 4.97,
    reviewCount: 35,
    amenities: ['WiFi', 'Climatisation', 'Cuisine équipée', 'Jardin', 'Terrasse', 'Excursions désert'],
    houseRules: [
      { title: 'Arrivée', description: 'Après 14h00' },
      { title: 'Départ', description: 'Avant 11h00' },
      { title: 'Pas de cigarette', description: 'Non fumeur' },
      { title: 'Respect de la culture locale', description: 'Tenue correcte demandée dans les espaces communs' },
      { title: 'Animaux non admis', description: 'Pas d\'animaux' },
      { title: 'Calme nocturne', description: 'Silence après 21h30' },
    ],
    host: {
      id: 'h7',
      name: 'Sonia Trabelsi',
      avatar: 'https://i.pravatar.cc/150?img=49',
      joinDate: 'Février 2019',
      responseRate: 100,
      responseTime: 'Dans l\'heure',
      isSuperhost: true,
      bio: 'Fille du désert, je propose des séjours authentiques à Tozeur depuis 5 ans. Je peux organiser des excursions sur les dunes et dans les oasis.',
    },
    reviews: [
      { id: 'r15', author: 'Pierre G.', avatar: 'https://i.pravatar.cc/150?img=2', date: 'Novembre 2023', rating: 5, comment: 'Expérience absolument unique ! Sonia est une hôte extraordinaire, pleine de conseils.' },
      { id: 'r16', author: 'Hana S.', avatar: 'https://i.pravatar.cc/150?img=30', date: 'Octobre 2023', rating: 5, comment: 'Maison magnifique, architecture sahélienne superbe. Le dîner sous les étoiles est un souvenir impérissable.' },
      { id: 'r17', author: 'Marc D.', avatar: 'https://i.pravatar.cc/150?img=10', date: 'Décembre 2023', rating: 5, comment: 'La meilleure expérience de voyage de ma vie ! Tozeur est fabuleux et cette maison est un bijou.' },
    ],
    minNights: 2,
    available: true,
    lat: 33.919,
    lng: 8.133,
  },
  {
    id: '8',
    title: 'Chalet Montagne Ain Draham',
    type: 'Maison',
    location: 'Ain Draham',
    wilaya: 'Jendouba',
    description:
      'Chalet de montagne à Ain Draham, la "Suisse tunisienne", perché à 800 mètres d\'altitude dans une forêt de chênes-lièges. Ce chalet en pierre et bois offre un panorama exceptionnel sur les montagnes du nord-ouest tunisien. En été, profitez de la fraîcheur naturelle. En hiver, la neige recouvre parfois les toits. Idéal pour les amateurs de trekking, VTT et nature.',
    shortDescription: 'Chalet en pierre et bois à 800m d\'altitude, vue montagne',
    images: [
      'https://picsum.photos/seed/ain1/800/600',
      'https://picsum.photos/seed/ain2/800/600',
      'https://picsum.photos/seed/ain3/800/600',
      'https://picsum.photos/seed/ain4/800/600',
      'https://picsum.photos/seed/ain5/800/600',
    ],
    price: 195,
    cleaningFee: 45,
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    beds: 4,
    rating: 4.80,
    reviewCount: 22,
    amenities: ['WiFi', 'Cheminée', 'Cuisine équipée', 'Parking', 'Terrasse', 'Vue montagne', 'Randonnée'],
    houseRules: [
      { title: 'Arrivée', description: 'Après 15h00' },
      { title: 'Départ', description: 'Avant 11h00' },
      { title: 'Pas de cigarette à l\'intérieur', description: 'Fumeurs en extérieur uniquement' },
      { title: 'Pas de fêtes', description: 'Lieu de détente et de calme' },
      { title: 'Animaux acceptés', description: 'Animaux de compagnie acceptés' },
      { title: 'Calme nocturne', description: 'Silence après 22h' },
    ],
    host: {
      id: 'h8',
      name: 'Mehdi Riahi',
      avatar: 'https://i.pravatar.cc/150?img=13',
      joinDate: 'Juillet 2022',
      responseRate: 92,
      responseTime: 'Dans les 3 heures',
      isSuperhost: false,
      bio: 'Montagnard dans l\'âme, j\'ai construit ce chalet de mes mains. Je connais chaque sentier d\'Ain Draham et serai ravi de vous guider.',
    },
    reviews: [
      { id: 'r18', author: 'Lucie V.', avatar: 'https://i.pravatar.cc/150?img=27', date: 'Septembre 2023', rating: 5, comment: 'Dépaysement total ! L\'air frais de la montagne, la vue magnifique... on ne voulait plus repartir.' },
      { id: 'r19', author: 'Kamel B.', avatar: 'https://i.pravatar.cc/150?img=19', date: 'Août 2023', rating: 4, comment: 'Chalet bien situé et confortable. Mehdi est très sympathique et donne de bons conseils de randonnée.' },
    ],
    minNights: 2,
    available: true,
    lat: 36.779,
    lng: 8.685,
  },
];

export const wilayasTunisie = [
  'Ariana', 'Béja', 'Ben Arous', 'Bizerte', 'Gabès', 'Gafsa', 'Jendouba',
  'Kairouan', 'Kasserine', 'Kébili', 'Kef', 'Mahdia', 'Manouba', 'Médenine',
  'Monastir', 'Nabeul', 'Sfax', 'Sidi Bouzid', 'Siliana', 'Sousse',
  'Tataouine', 'Tozeur', 'Tunis', 'Zaghouan',
];

export const conversations: Conversation[] = [
  {
    id: 'c1',
    participantName: 'Yasmine Ben Ali',
    participantAvatar: 'https://i.pravatar.cc/150?img=47',
    propertyTitle: 'Villa Blanche de Sidi Bou Said',
    propertyImage: 'https://picsum.photos/seed/sidi1/100/100',
    lastMessage: 'Bonjour ! Votre réservation est confirmée pour le 15 juin.',
    lastTime: '10:30',
    unread: 1,
    messages: [
      { id: 'm1', senderId: 'h1', content: 'Bonjour ! Merci pour votre réservation. J\'ai bien reçu votre demande.', timestamp: '09:00', isOwn: false },
      { id: 'm2', senderId: 'me', content: 'Bonjour Yasmine, merci ! Avez-vous des informations sur le parking ?', timestamp: '09:15', isOwn: true },
      { id: 'm3', senderId: 'h1', content: 'Oui bien sûr ! Il y a un parking privé pouvant accueillir 2 voitures. Je vous enverrai le code d\'accès la veille.', timestamp: '09:45', isOwn: false },
      { id: 'm4', senderId: 'me', content: 'Parfait, merci beaucoup !', timestamp: '10:00', isOwn: true },
      { id: 'm5', senderId: 'h1', content: 'Bonjour ! Votre réservation est confirmée pour le 15 juin.', timestamp: '10:30', isOwn: false },
    ],
  },
  {
    id: 'c2',
    participantName: 'Nadia Sellami',
    participantAvatar: 'https://i.pravatar.cc/150?img=45',
    propertyTitle: 'Villa Jasmin Hammamet',
    propertyImage: 'https://picsum.photos/seed/hamm1/100/100',
    lastMessage: 'Bonne arrivée ! N\'hésitez pas si vous avez besoin de quoi que ce soit.',
    lastTime: 'Hier',
    unread: 0,
    messages: [
      { id: 'm6', senderId: 'h3', content: 'Bonjour ! Bienvenue à la Villa Jasmin. Avez-vous bien trouvé la maison ?', timestamp: 'Hier 16:00', isOwn: false },
      { id: 'm7', senderId: 'me', content: 'Oui merci ! La villa est superbe, exactement comme sur les photos.', timestamp: 'Hier 16:30', isOwn: true },
      { id: 'm8', senderId: 'h3', content: 'Bonne arrivée ! N\'hésitez pas si vous avez besoin de quoi que ce soit.', timestamp: 'Hier 16:45', isOwn: false },
    ],
  },
  {
    id: 'c3',
    participantName: 'Sonia Trabelsi',
    participantAvatar: 'https://i.pravatar.cc/150?img=49',
    propertyTitle: 'Maison Tozeur Oasis',
    propertyImage: 'https://picsum.photos/seed/tozeur1/100/100',
    lastMessage: 'Je peux organiser une excursion au Chott el-Jérid si vous êtes intéressé !',
    lastTime: 'Lun',
    unread: 2,
    messages: [
      { id: 'm9', senderId: 'me', content: 'Bonjour Sonia, je souhaiterais réserver pour 4 nuits en novembre.', timestamp: 'Lun 11:00', isOwn: true },
      { id: 'm10', senderId: 'h7', content: 'Bonjour ! Avec plaisir, novembre est une période idéale pour Tozeur.', timestamp: 'Lun 11:30', isOwn: false },
      { id: 'm11', senderId: 'h7', content: 'Je peux organiser une excursion au Chott el-Jérid si vous êtes intéressé !', timestamp: 'Lun 11:32', isOwn: false },
    ],
  },
];
